### ISSUE TITLE
Additional argument to the "ske kubeconfig login" command

### ISSUE THREAD

**Issue by tchelovilar** [stackitcloud/stackit-cli#358]
Currently, the `stackit ske kubeconfig login` command expects the `ClusterName` and `STACKITProjectID` from the cluster extensions section from the `kubeconfig` file, but unfortunately, the terraform [kubernetes provider doesn't have support ](https://github.com/hashicorp/terraform-provider-kubernetes/issues/2506) for that. 

I wonder if those arguments could be passed optionally as command arguments or as environment variables.

This [PR](https://github.com/stackitcloud/terraform-provider-stackit/issues/380) is an example of what I'm trying to do.

**Comment by Kumm-Kai** [comment]
Hi @tchelovilar thanks for your request.

The `ske kubeconfig login` command is meant to only be used with a kubeconfig created via `ske kubeconfig create NAME --login` or the SKE-API.

We want to provide a simple user experience, therefore we decided to use the `clusters[].cluster.extensions` object instead of allowing additional flags.

But we can definitely implement https://github.com/stackitcloud/terraform-provider-stackit/issues/380 to make creating the kubeconfig in terraform easier.

In the meantime, you can manually retrieve the login kubeconfig and provide it to the Kubernetes TF provider:
```
provider "kubernetes" {
  config_path = "~/.kube/config"
}
```

Hope this helps 🙂

**Comment by tchelovilar** [comment]
Hi @Kumm-Kai,

Thank you for the fast answer, the config_path works and it's good, but the option to set the provider dynamically would be great and remove 1 manual step to generate the config file.

Best :D

**Comment by vicentepinto98** [comment]
Hi @tchelovilar, I'll close this issue as we won't add any additional flags to the `ske kubeconfig login` command, like explained above.

We'll keep track of the enhancement to the terraform provider in the respective issue https://github.com/stackitcloud/terraform-provider-stackit/issues/380
